### PR TITLE
Change type and size of icon.icns the same as previous icon

### PR DESCRIPTION
**Pull request by Thisak**
update icon the same type and size from previous icns

### CODE REVIEW

**Comment by KumanoTanaka** [comment]
@Thisak 
can you also upgrade `icon.ico` ?

**Comment by Thisak** [comment]
@KumanoTanaka OK I will upgrade size of icon.ico

**Comment by Thisak** [comment]
@KumanoTanaka  OK I will check it.

**Comment by Thisak** [comment]
@KumanoTanaka I have upgrade for icon.ico and icon.icns

**Pull request merged**
